import = ["~/.config/alacritty/theme.toml"]

[bell]
animation = "EaseOutExpo"
duration = 100

[font]
size = 10.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[window]
decorations = "none"
opacity = 0.9375

[window.dimensions]
columns = 100
lines = 50
